package com.algolia.instantsearch.insights

import com.algolia.instantsearch.insights.internal.data.local.model.InsightsEventDO

public interface Insights : HitsAfterSearchTrackable, FilterTrackable {

    /**
     * Application ID for the Insights API
     */
    public val applicationID: String

    /**
     * API key for the Insights API
     */
    public val apiKey: String

    /**
     * Change this variable to `true` or `false` to disable Insights, opting-out the current session from tracking.
     */
    public var enabled: Boolean

    /**
     * Change this variable to change the default debouncing interval. Values lower than 15 minutes will be ignored.
     */
    public var debouncingIntervalInMinutes: Long?

    /**
     * Set a user identifier that will override any event's.
     *
     * Depending if the user is logged-in or not, several strategies can be used from a sessionId to a technical identifier.
     * You should always send pseudonymous or anonymous userTokens.
     */
    public var userToken: String?

    /**
     * Change this variable to change the default amount of event sent at once.
     */
    public var minBatchSize: Int

    /**
     * Change this variable to `true` or `false` to enable or disable logging.
     * Use a filter on tag `Algolia Insights` to see all logs generated by the Insights library.
     */
    public var loggingEnabled: Boolean

    // Note: track method removed from public API as InsightsEventDO is internal.
    // Use the specific tracking methods from HitsAfterSearchTrackable and FilterTrackable instead.

    /**
     * Insights configuration.
     */
    public class Configuration(

        /**
         * Maximum amount of time in milliseconds before a connect timeout
         */
        public val connectTimeoutInMilliseconds: Long = 5000,

        /**
         * Maximum amount of time in milliseconds before a read timeout.
         */
        public val readTimeoutInMilliseconds: Long = 5000,

        /**
         * Default User Token.
         */
        public val defaultUserToken: String? = null,

        /**
         * Defines if the timestamps of the events should be automatically attributed if not provided while calling the
         * event capturing function. If set to `false`, the events will be sent without timestamp value and will be
         * automatically attributed on the server, which may affect the accuracy of the events.
         */
        public val generateTimestamps: Boolean = true,
    )

    public companion object
}
