package com.algolia.instantsearch.telemetry

public expect enum class ComponentParam {
    undefined,
    apiKey,
    appID,
    attribute,
    bounds,
    clearMode,
    client,
    facets,
    filter,
    filterGroupForAttribute,
    filterGroupIDs,
    groupName,
    hierarchicalAttributes,
    indexName,
    infiniteScrolling,
    item,
    items,
    operator,
    orderedFacets,
    priority,
    range,
    searchTriggeringMode,
    searcher,
    selected,
    selectionMode,
    selectionModeForAttribute,
    selections,
    separator,
    showItemsOnEmptyQuery,
}
