name: Deploy

on:
    workflow_dispatch:

env:
    GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
    publish:
        name: Publish to Sonatype
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Configure JDK
                uses: actions/setup-java@v4
                with:
                    distribution: temurin
                    java-version-file: .tool-versions

            -   name: Setup Android SDK
                uses: android-actions/setup-android@v3

            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v3

            -   name: Upload Artifacts
                run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
                env:
                    ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
                    ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
                    ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
                    ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_PRIVATE_KEY_ID }}
                    ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PRIVATE_KEY_PASSWORD }}
